name: release-pr-package

# SECURITY NOTE:
# pull_request_target is used to run the workflow on pull requests from ANY FORK!
# This is required to have access to the secret to publish the PR to npm.
# For that reason, any outside collaborator requires approval from a contributor.
# https://github.com/redhat-developer/red-hat-developer-hub-theme/settings/actions
on:
  pull_request_target:
    types: [opened, synchronize, reopened]

jobs:
  release-pr-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test
      - name: Publish to npm
        run: |
          # bash
          full_sha="${{ github.event.pull_request.head.sha }}"
          short_sha="${full_sha::7}"
          version="0.0.0-pr-${{ github.event.number }}-${short_sha}"
          yarn version --new-version "$version" --no-git-tag-version
          yarn publish --access public --tag latest-pr
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Add comment to PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          script: |
            const fullSha = '${{ github.event.pull_request.head.sha }}';
            const shortSha = fullSha.slice(0, 7);
            const version = `0.0.0-pr-${{ github.event.number }}-${shortSha}`;
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `New package is available at: \`@opensource-sig/devex-opa-theme@${version}\``
            });
